# This is the main config. Parameters are update and possibly overwritten by dataset dependent configs.
model:
  mode: train # "train", "test", "predict"
  batch_size: 32
  epochs: 20
  learning_rate: 0.01
  class_weighted_loss: True
  load_name: None
  save_name: fsconv
  feature_extractor:
    type: fsconv # "fsconv", "simple_cnn", "mobilenetv2", "resnet50", "efficientnetb0", "efficientnetb1"
    global_max_pooling: True
    num_output_features: 0 # feature dimension of feature extractor output, set to 0 to skip this layer
    output_activation: sigmoid # sigmoid, relu
  head:
    type: deterministic # deterministic, gp, bnn
    deterministic:
      dropout: 0.0
      number_hidden_units: 0 # feature dimension of hidden layer, set to 0 to skip this layer
    gp:
      inducing_points: 200
    bnn:
      number_hidden_units: 100
      kl_loss_factor: 1


dataset_config: ./dataset_dependent/sicapv2/config.yaml

logging:
  log_experiment: True
  run_name: test
  tracking_url: /home/arne/projects/mlruns