name: camelyon16_scripts
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py38h06a4308_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1h=h7b6447c_0
  - pip=20.2.4=py38_0
  - python=3.8.5=h7579374_1
  - readline=8.0=h7b6447c_0
  - setuptools=50.3.0=py38hb0f4dca_1
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - cycler==0.10.0
    - decorator==4.4.2
    - et-xmlfile==1.0.1
    - imagecodecs==2020.5.30
    - imageio==2.9.0
    - jdcal==1.4.1
    - kiwisolver==1.3.0
    - matplotlib==3.3.2
    - networkx==2.5
    - numpy==1.19.3
    - opencv-python==4.4.0.44
    - openpyxl==3.0.5
    - openslide-python==1.1.2
    - pandas==1.1.3
    - pillow==8.0.1
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pywavelets==1.1.1
    - scikit-image==0.18.0
    - scipy==1.5.4
    - six==1.15.0
    - tifffile==2020.12.8
    - xlrd==1.2.0
prefix: /home/arne/miniconda3/envs/camelyon16_scripts
